version: '3.9'
services:
    postgresql-server:
        container_name: postgresql-server
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postpasswd
        ports:
            - "5432:5432"
    parking-control: 
        container_name: parking-control
        build: .
        environment: 
            POSTGRES_URL: jdbc:postgresql://postgresql-server/postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postpasswd
        ports:
            - "8080:8080"
        depends_on:
            - postgresql-server
